# app.yaml
runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  ENV: "production"
  DEBUG: "False"
  DATABASE_URL: "postgresql://user:password@localhost:5432/mydatabase"
# Optional: Uncomment the following lines if you want to use Cloud SQL
this is sai from the future
  # CLOUD_SQL_CONNECTION_NAME: "your-project